---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: myapp-ingress-tls
  namespace: istio-system
spec:
  secretName: myapp-ingress-tls  # Used in Istio Gateway `credentialName`
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: myapp.myorg.com
  dnsNames:
    - myapp.myorg.com
  issuerRef:
    name: cas-issuer
    kind: GoogleCASClusterIssuer
    group: cas-issuer.jetstack.io
