global:
  pilotCertProvider: gcp_cas
  meshID: mesh1
  multiCluster:
    clusterName: boreal-mode-295611-gke-int-s-1
  network: network1

meshConfig:
  trustDomain: "cluster.local"
  accessLogFile: /dev/stdout

pilot:
  autoscaleEnabled: true
  env:
    # Optional: increase XDS push limits
    PILOT_PUSH_THROTTLE: "0"
  serviceAccount:
    name: istio-cas-ksa

  # Optional debug logs
  logLevel: "default:info"
  componentLogLevel: "misc:debug"

  # This is important for workload identity to propagate down
  nodeSelector:
    iam.gke.io/gke-metadata-server-enabled: "true"

  # Mount credentials from KSA that has GCP CAS access
  extraVolumeMounts:
    - name: workload-identity-creds
      mountPath: /var/run/secrets/workload-identity
      readOnly: true

  extraVolumes:
    - name: workload-identity-creds
      projected:
        sources:
          - serviceAccountToken:
              path: istio-token
              expirationSeconds: 7200
              audience: "https://privateca.googleapis.com/"

# Required metadata to pull certs from GCP CAS
values:
  meshConfig:
    defaultConfig:
      proxyMetadata:
        GCP_METADATA_CERT_URL: "https://privateca.googleapis.com/v1/projects/boreal-mode-295611/locations/europe-west1/caPools/istio-ca-pool"

# Service account used by Istiod (should be bound to GCP SA using Workload Identity)
serviceAccount:
  name: istio-cas-ksa
