apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app-vs
  namespace: hello-world
spec:
  hosts:
    - myapp.myorg.com
  gateways:
    - istio-system/app-gateway
  http:
    - route:
        - destination:
            host: hello-world
            port:
              number: 80
